name: magic_hat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Code generation
  freezed: ^2.5.2
  freezed_annotation: ^2.4.3
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

  # Api  
  dio: ^5.5.0+1
  pretty_dio_logger: ^1.3.1

  # Core
  get_it: ^7.7.0

  # State management
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  test: ^1.25.2

flutter:
  uses-material-design: true
